import type {
  ArchitectureGraph,
  DependencyGraph,
  RepoScan,
} from "../domain/schemas.js";
import type { ComponentCatalog } from "../core/discover/catalog.js";

/**
 * Deterministic Markdown renderers for derived artifacts. These produce the
 * human-reviewable half of each artifact (the canonical JSON is the machine
 * half). Every renderer is a pure function of its input and emits stable output
 * (sorted, no timestamps) so git diffs reflect real changes only.
 *
 * A shared header notes that the file is generated, so a human never edits it
 * by hand expecting the edit to survive regeneration.
 */
function header(title: string, generator: string): string {
  return `<!-- GENERATED by ${generator} — do not edit by hand; edits are overwritten on regenerate. -->\n\n# ${title}\n`;
}

function pct(n: number, total: number): string {
  return total === 0 ? "0%" : `${((n / total) * 100).toFixed(1)}%`;
}

export function renderRepositorySummary(scan: RepoScan): string {
  const langRows = Object.entries(scan.languages)
    .sort((a, b) => b[1].loc - a[1].loc || (a[0] < b[0] ? -1 : 1))
    .map(([lang, s]) => `| ${lang} | ${s.files} | ${s.loc} | ${pct(s.bytes, scan.totalBytes)} |`);

  const entrypoints = scan.files.filter((f) => f.isEntrypoint).map((f) => f.path);
  const tests = scan.files.filter((f) => f.isTest).length;
  const docs = scan.files.filter((f) => f.isDoc).length;

  return [
    header("Repository Summary", scan.generator),
    "",
    `- **Files:** ${scan.fileCount}`,
    `- **Total size:** ${(scan.totalBytes / 1024).toFixed(1)} KiB`,
    `- **Languages:** ${Object.keys(scan.languages).length}`,
    `- **Test files:** ${tests}`,
    `- **Doc files:** ${docs}`,
    `- **Scan fingerprint:** \`${scan.scanHash}\``,
    "",
    "## Languages",
    "",
    "| Language | Files | LOC | Bytes |",
    "| --- | --- | --- | --- |",
    ...langRows,
    "",
    "## Entrypoints",
    "",
    entrypoints.length ? entrypoints.map((e) => `- \`${e}\``).join("\n") : "_None detected._",
    "",
  ].join("\n");
}

export function renderLanguageStats(scan: RepoScan): string {
  const rows = Object.entries(scan.languages)
    .sort((a, b) => b[1].loc - a[1].loc || (a[0] < b[0] ? -1 : 1))
    .map(([lang, s]) => `| ${lang} | ${s.files} | ${s.loc} | ${s.bytes} |`);
  return [
    header("Language Statistics", scan.generator),
    "",
    "| Language | Files | LOC | Bytes |",
    "| --- | --- | --- | --- |",
    ...rows,
    "",
  ].join("\n");
}

export function renderDependencyGraph(graph: DependencyGraph): string {
  const topFanOut = countBy(graph.edges.map((e) => e.from)).slice(0, 15);
  const topFanIn = countBy(graph.edges.map((e) => e.to)).slice(0, 15);

  return [
    header("Dependency Graph", graph.generator),
    "",
    `- **Files (nodes):** ${graph.nodes.length}`,
    `- **Internal edges:** ${graph.edges.length}`,
    `- **External dependencies:** ${graph.externalDeps.length}`,
    `- **Import cycles:** ${graph.cycles.length}`,
    `- **Unresolved relative imports:** ${graph.unresolvedImports}`,
    "",
    "## Most depended-upon files (fan-in)",
    "",
    ...topFanIn.map(([p, c]) => `- \`${p}\` — ${c}`),
    "",
    "## Files with most dependencies (fan-out)",
    "",
    ...topFanOut.map(([p, c]) => `- \`${p}\` — ${c}`),
    "",
    "## Cycles",
    "",
    graph.cycles.length
      ? graph.cycles.map((c, i) => `${i + 1}. ${c.map((n) => `\`${n}\``).join(" → ")}`).join("\n")
      : "_No import cycles detected._",
    "",
    "## External dependencies",
    "",
    graph.externalDeps.length
      ? graph.externalDeps.map((d) => `- **${d.name}**${d.version ? ` (${d.version})` : ""} — _${d.source}_`).join("\n")
      : "_None declared._",
    "",
  ].join("\n");
}

export function renderArchitecture(arch: ArchitectureGraph): string {
  const moduleRows = arch.modules
    .map((m) => {
      const met = arch.metrics[m.id];
      return `| \`${m.id}\` | ${m.fileCount} | ${m.languages.join(", ")} | ${met?.fanIn ?? 0} | ${met?.fanOut ?? 0} | ${met?.instability ?? 0} |`;
    })
    .join("\n");

  const layerRows = arch.layers
    .map((layer, i) => `- **Layer ${i}:** ${layer.map((m) => `\`${m}\``).join(", ")}`)
    .join("\n");

  return [
    header("Architecture", arch.generator),
    "",
    `- **Modules:** ${arch.modules.length}`,
    `- **Module edges:** ${arch.edges.length}`,
    `- **Module cycles:** ${arch.cycles.length}`,
    `- **Layers:** ${arch.layers.length}`,
    "",
    "## Modules",
    "",
    "| Module | Files | Languages | Fan-in | Fan-out | Instability |",
    "| --- | --- | --- | --- | --- | --- |",
    moduleRows || "| _none_ | | | | | |",
    "",
    "## Layers (0 = foundational)",
    "",
    layerRows || "_No modules._",
    "",
    "## Module cycles",
    "",
    arch.cycles.length
      ? arch.cycles.map((c, i) => `${i + 1}. ${c.map((m) => `\`${m}\``).join(" → ")}`).join("\n")
      : "_No module cycles detected._",
    "",
  ].join("\n");
}

export function renderComponentCatalog(cat: ComponentCatalog): string {
  const section = (title: string, items: string[]) =>
    [`## ${title}`, "", items.length ? items.map((i) => `- ${i}`).join("\n") : "_None._", ""].join("\n");

  return [
    header("Component Catalog", cat.generator),
    "",
    section("Services", cat.services.map((s) => `\`${s.path}\` — ${s.reason}`)),
    section("Modules", cat.modules.map((m) => `\`${m.id}\` (${m.fileCount} files)`)),
    section("Entrypoints", cat.entrypoints.map((e) => `\`${e}\``)),
    section("Test suites", cat.tests.map((t) => `\`${t}\``)),
    section("Documentation", cat.docs.map((d) => `\`${d}\``)),
    section("Owners", cat.owners.map((o) => `\`${o.pattern}\` → ${o.owners.join(", ")}`)),
  ].join("\n");
}

function countBy(items: string[]): Array<[string, number]> {
  const counts = new Map<string, number>();
  for (const i of items) counts.set(i, (counts.get(i) ?? 0) + 1);
  return [...counts.entries()].sort((a, b) => b[1] - a[1] || (a[0] < b[0] ? -1 : 1));
}
